app/models/booking.rb, app/models/movie_set.rb, app/models/user.rb, db/migrate/20191118150633_add_columns_to_users.rb, db/migrate/20191118151651_create_movie_sets.rb, db/migrate/20191118152735_create_bookings.rb, db/schema.rb, test/models/booking_test.rb, test/models/movie_set_test.rb
@Castrax What do you think of these 3 models?
=> 3 core models validations associations

app/controllers/movie_sets_controller.rb, app/views/movie_sets/index.html.erb, app/views/movie_sets/show.html.erb, config/routes.rb, test/controllers/movie_sets_controller_test.rb
@Castrax Can you merge that asap please?
=> movie_set controller creation

app/controllers/movie_sets_controller.rb, db/seeds.rb
@Castrax  Begining of the seed seed + show action in the MovieSets controller
=> beginning of the seed and show action in the movie sets controller

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
@coleopard, could you please review my code ?
=> homepage & front end variables

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_index_card.scss, app/controllers/movie_sets_controller.rb, app/views/movie_sets/index.html.erb, config/routes.rb, test/controllers/movie_sets_controller_test.rb
Hi there can you review my first version of the index please.
Many thanks @Castrax 
We may have some conflicts with @coleopard
=> first version of index

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search_form.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
Hello ! @Castrax Here's the footer navbar to review
=> navbar-footer start

app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_show_movie_set_details.scss, app/views/movie_sets/show.html.erb, db/seeds.rb
@Castrax Carousel + initialisation de la seed + première mise en forme de la show
=> carousel + affichage de la show

app/javascript/packs/application.js, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, package.json, yarn.lock
@Castrax J'ai ajouté datepickr pour les dates dans le navbar
=> Navbar footer

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_navbar.html.erb
Hello @rijarajohnson ,
I have finished the login part :)
=> login pages

app/controllers/bookings_controller.rb, app/controllers/movie_sets_controller.rb, app/controllers/pages_controller.rb, app/views/movie_sets/show.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb
@Castrax booking create and pages#dashboard with controller
=> booking create

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_index_movie_set_card.scss, app/views/movie_sets/index.html.erb
Index finalisé à merger @Castrax
=> Index create

app/views/shared/_navbar.html.erb
=> navbar different for user and non-user

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_search_form.scss, app/controllers/movie_sets_controller.rb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
@coleopard Hey there, i've improved the search. 
Could you please review my code 
xxx
=> search improvements

app/assets/stylesheets/components/_show_movie_set_details.scss, app/views/movie_sets/show.html.erb, db/seeds.rb
added description cards on the shows @jonathansanturbano
=> show-description

app/javascript/packs/application.js, app/views/movie_sets/show.html.erb, app/views/shared/_navbar.html.erb
=> booking design done

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_index_movie_set_card.scss, app/assets/stylesheets/components/_map.scss, app/controllers/movie_sets_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/movie_set.rb, app/views/movie_sets/index.html.erb, config/initializers/geocoder.rb, db/migrate/20191120100105_add_coordinates_to_movie_sets.rb, db/schema.rb, package.json, yarn.lock
@coleopard, what do you think about my map ?
=> map welldone

app/assets/stylesheets/components/_card-dashboard.scss, app/assets/stylesheets/components/_search_form.scss, app/views/pages/dashboard.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
@coleopard, can you please review ?
=> hp dashboard

app/controllers/movie_sets_controller.rb, app/views/movie_sets/index.html.erb, app/views/shared/_navbar.html.erb
hello @coleopard could you please accept this awesome PR 
Many thanks 
xxx
=> search optimization

app/views/movie_sets/index.html.erb, app/views/shared/_navbar.html.erb
=> search ended

app/javascript/packs/application.js
=> datebooking

config/environments/production.rb
=> production

app/assets/stylesheets/components/_show_movie_set_details.scss, app/views/movie_sets/show.html.erb
@rijarajohnson can you review the css show? thanks
=> css show final

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_tabs_dashboard.scss, app/views/pages/dashboard.html.erb
@jonathansanturbano Can you please have a look on my PR ?
=> dashboard tab

app/controllers/movie_sets_controller.rb, app/views/movie_sets/show.html.erb, db/seeds.rb
=> encart grise

app/controllers/pages_controller.rb, app/views/pages/dashboard.html.erb
Hey @Castrax please find my awesome PR
=> recuperation des movie sets create

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> navbar-modifs

app/views/movie_sets/show.html.erb
=> last booking done

app/assets/stylesheets/components/_tabs_dashboard.scss, app/views/pages/dashboard.html.erb
hey @jonathansanturbano can you have a look on this PR please ?
=> css double dashboard

app/assets/stylesheets/components/_map.scss, app/controllers/movie_sets_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/movie_sets/_info_window.html.erb, app/views/movie_sets/index.html.erb, app/views/movie_sets/show.html.erb
=> index result number and map popup

app/assets/stylesheets/components/_index_movie_set_card.scss, app/assets/stylesheets/components/_map.scss, app/views/movie_sets/index.html.erb
@jonathansanturbano can you review the index and the map css? thanks
=> css de l'index en 720

app/views/pages/home.html.erb
=> search bar home styling

app/views/pages/dashboard.html.erb
=> dashboard my bookings cards

app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_show_movie_set_details.scss, app/views/movie_sets/show.html.erb
=> show css in progress

Gemfile, Gemfile.lock, app/assets/stylesheets/animate_and_overrides.css.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_flash.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/javascript/packs/application.js, app/views/movie_sets/edit.html.erb, app/views/shared/_alertshow.html.erb, app/views/shared/_form.html.erb, app/views/shared/_notice.html.erb, package.json, yarn.lock
=> form alert

app/views/pages/dashboard.html.erb
Dashboard fix dude @jonathansanturbano
=> dashboard fix
